name: build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-repo-scan:
    name: Trivy Repo Scan & Upload to Security Tab
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  reviewdog-pr-check:
    name: Trivy PR Check
    runs-on: ubuntu-20.04
    needs: trivy-repo-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/scripts/install.sh | sh
          sudo mv trivy /usr/local/bin/

      - name: Install Reviewdog
        run: |
          curl -sfL https://github.com/reviewdog/reviewdog/releases/download/v0.14.0/reviewdog_linux_amd64 -o /usr/local/bin/reviewdog
          chmod +x /usr/local/bin/reviewdog

      - name: Run Trivy with Reviewdog and output to PR
        run: |
          trivy fs . --severity LOW,MEDIUM,HIGH,CRITICAL --exit-code 0 | reviewdog -f=trivy -name="Trivy Scan" -reporter=github-pr-check -filter-mode=nofilter -level=warning
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
